import 'package:flutter/material.dart';
//import 'package:firebase_core/firebase_core.dart'; // Import this
//import 'firebase_options.dart'; // This file is generated by flutterfire configure (optional)
// If you manually added json/plist files, you might not need the options file yet,
// but let's stick to the simplest manual init if you don't use the CLI.

import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/diary_list_screen.dart';
import 'screens/add_diary_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Required for async main

  // Initialize Firebase
  // If you used the CLI: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // If you manually placed the JSON files:
  // await Firebase.initializeApp();

  runApp(const CloudyLogApp());
}

class CloudyLogApp extends StatelessWidget {
  const CloudyLogApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CloudyLog',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const HomeScreen(),
        '/diary_list': (context) => const DiaryListScreen(),
        '/add_diary': (context) => const AddDiaryScreen(),
      },
    );
  }
}
